export default {
        cart: [],
        buyer: [],
        orders: [],
        products: [
          {
            'id': '1',
            'image': 'https://us.123rf.com/450wm/mashe/mashe1201/mashe120100057/11963943-flor-de-cempas%C3%BAchil-franc%C3%A9s.jpg?ver=6',
            'title': 'Amboleas',
            'price': 25,
            'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
          },
          {
            'id': '2',
            'image': 'https://plant.gt/productos/images/opuntia-ficus-indica-210819.jpg',
            'title': 'Nopal',
            'price': 50,
            'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
          },
          {
            'id': '3',
            'image': 'https://cdn.webshopapp.com/shops/30495/files/371963433/cactus-euphorbia-ingens-xxl.jpg',
            'title': 'Cactus',
            'price': 50,
            'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
          },
          {
            'id': '4',
            'image': 'https://cdn.pixabay.com/photo/2019/05/12/10/23/damiana-4197636_960_720.jpg',
            'title': 'Damianas',
            'price': 40,
            'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
          },
          {
            'id': '5',
            'image': 'https://upload.wikimedia.org/wikipedia/commons/5/55/Turnera_subulata.jpg',
            'title': 'Turnera',
            'price': 45,
            'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
          },
          {
            'id': '6',
            'image': 'https://us.123rf.com/450wm/nikkikii/nikkikii1812/nikkikii181200058/118037753-la-gota-de-roc%C3%ADo-dorada-o-duranta-repens-l-se-cultiva-ampliamente-como-planta-ornamental-en-las-regi.jpg?ver=6',
            'title': 'Duranta dorada',
            'price': 35,
            'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
          },
          {
            'id': '7',
            'image': 'https://fyf.tac-cdn.net/images/products/large/N-007.jpg?auto=webp&quality=60&width=690',
            'title': 'Cipress',
            'price': 155,
            'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
          },
        ],
      };